version: "3.3"

services:
  web:
    build:
      context: .
    container_name: off_web
    depends_on:
      - db
    restart: always
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_DB_NAME
      - DJANGO_DB_USER
      - DJANGO_DB_PASSWORD
      - DJANGO_DB_HOST
      - DJANGO_DB_PORT
      - DJANGO_EMAIL_HOST
      - DJANGO_EMAIL_HOST_USER
      - SENDGRID_KEY
    volumes:
      - ./django:/off_by_one/django
      # - static_volume:/off_by_one/django/static_files
    command: >
      sh -c "./manage.py runserver 0.0.0.0:8000"
  db:
    container_name: off_db
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRESS_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  # static_volume:
